### ISSUE TITLE
SetOnClick doesn't work

### ISSUE THREAD

**Issue by eddydn** [MostafaNasiri/CircularPulsingButton#1]
button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(MainActivity.this, "Hello", Toast.LENGTH_SHORT).show();
            }
        });

I've try to set OnClickListener but it don't work

**Comment by MostafaNasiri** [comment]
Thank you for reporting this serious bug. It's fixed now in version 1.1.1.
